# Generated by Django 5.0.6 on 2024-05-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_remove_produitnc_id_produitnc_produit_ptr_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(choices=[('Alimenatire', 'Alimenatire'), ('Mb', 'Meuble'), ('Sn', 'Sanitaire'), ('Vs', 'Vaisselle'), ('Vt', 'Vetement'), ('Jx', 'Jouets'), ('Lg', 'Ligne de Maison'), ('Bj', 'Bijoux'), ('Dc', 'Décor')], default='Alimentaire', max_length=50),
        ),
    ]
